WIP: Make sure Include is in the main configuration file when drop-in directory is used
willshersystems/ansible-sshd pull request #178
Opened 2022-04-06 20:21 UTC by Jakuje

This implements sanity check to make sure the configuration files on RHEL9 and Fedora, which are placed in drop-in directory are really applied by checking the include directive in the main configuration file.

There are also some unrelated changes which I hit while testing locally and which blocked me from follow-up testing including the recently introduced FIPS check, which turned out still quite problematic and I was not able to make it working in CentOS 7 so far (so keeping the PR in WIP state so far).

2022-04-28 09:08 UTC, Jakuje commented
@mattwillsher @richm can you have a look?

2022-04-28 12:43 UTC, mattwillsher commented
It looks ok to me.

We are getting quite a lot of logic and long conditionals now. I'm wondering how far we are off this needing a refactor or even rewrite

2022-05-02 12:10 UTC, Jakuje commented
> > We are getting quite a lot of logic and long conditionals now. I'm wondering how far we are off this needing a refactor or even rewrite
> 
> Yeah - probably time for a module

Thank you for the comments. You are right, the conditions are getting longer. I can think of some reshuffling specific tasks to different tasks files to make it shorter and more readable. Do you have some specific recommendation except for rewriting all of that into module?

2022-05-02 14:00 UTC, richm commented
> > > We are getting quite a lot of logic and long conditionals now. I'm wondering how far we are off this needing a refactor or even rewrite
> > 
> > 
> > Yeah - probably time for a module
> 
> Thank you for the comments. You are right, the conditions are getting longer. I can think of some reshuffling specific tasks to different tasks files to make it shorter and more readable. Do you have some specific recommendation except for rewriting all of that into module?

Not specifically, no

2022-05-02 17:03 UTC, Jakuje commented
> Not specifically, no

So far I only split the huge install.yml to smaller parts to get rid of some conditions. Not sure if it is much better. Any other suggestions how to make it more readable would be welcomed.

In the meantime, I added support for recent ubuntu 22.04, which also finally supports drop-in directory. I can split this work into separate PR if needed.

2022-05-09 10:20 UTC, Jakuje commented
@richm or @mattwillsher  is there something else to address or does it look ok to you?

2022-05-09 13:33 UTC, mattwillsher commented
Looks ok to me

2022-05-09 14:20 UTC, richm commented on tasks/check_fips.yml
> +  slurp:
I've been told that there is no plan to require FQCN for built-ins in any foreseeable release of Ansible. I would suggest adding the suppression to .ansible-lint

2022-05-09 17:38 UTC, Jakuje commented on tasks/check_fips.yml
> +  slurp:
I already added it in previous PR (hopefully right). It makes the action not fail, but still reports these issues:

https://github.com/willshersystems/ansible-sshd/blob/master/.ansible-lint#L4

2022-05-09 17:49 UTC, richm commented on tasks/check_fips.yml
> +  slurp:
ack - lgtm

2022-05-10 12:54 UTC, ep69 requested changes

2022-05-10 12:54 UTC, ep69 commented on README.md
> +are checked for presence and new keys are generated if they aremissing.
Typo: `aremissing`

2022-05-10 13:15 UTC, Jakuje commented on README.md
> +are checked for presence and new keys are generated if they aremissing.
Thanks. Fixed and rebased.

2022-05-10 13:15 UTC, Jakuje commented on README.md
> +defailt `Include` directive from `__sshd_defaults` dict.
Thanks. Fixed and rebased.

2022-05-10 14:48 UTC, merged

2022-05-10 19:12 UTC, Jakuje commented
@mattwillsher do you want to take care of the release or should I draft something? I think it still involves the manual step of publishing the role on the galaxy.

2022-05-10 19:36 UTC, mattwillsher commented
To summarise for the release notes:

- adds support for Ubuntu 22.04
- improved support for RHEL9 and Fedora use of drop-in config
- genera quality improvements

2022-05-11 06:10 UTC, Jakuje commented
I would probably add points like this as there is a bit more changes since last release:

 * Support for Ubuntu 22.04 with drop-in directory (71eab11)
 * When using drop-in directory, verify the main configuration file has include directive (#178)
 * Tests improvements and general maintenance
 * Ensure the needed facts are available (e24ff31)
 * Filter out incompatible host keys on FIPS systems (#173)

https://github.com/willshersystems/ansible-sshd/compare/v0.14.1...master

2022-05-12 07:24 UTC, mattwillsher commented
v0.15.0 released and uploaded to Galaxy. Thanks all.