Manage SSH Certificates
willshersystems/ansible-sshd pull request #252
Opened 2023-08-31 12:27 UTC by EmyLIEUTAUD

**Enhancement:**
- Deploy User CA on the system
- Configure principals (optional)

**Reason:**
This allows you to configure and manage the SSH server to authenticate via certificates. 
Improves SSH authentication security: certificates have a validity period, unlike SSH keys.

More information on SSH certificates is available here: [Managing SSH Access at Scale with HashiCorp Vault](https://www.hashicorp.com/blog/managing-ssh-access-at-scale-with-hashicorp-vault).

**Result:**
All tests passed.
The related documentation is available and an example can be found in ```examples/example-use-certificates.yml```.

**Issue Tracker Tickets (Jira or BZ if any):** -

2023-08-31 12:55 UTC, Jakuje commented on tasks/certificates.yml
> +    mode: '0600'
I find it confusing that you are making a file with `.pem` extension which lists SSH keys in non-PEM format.

2023-08-31 12:56 UTC, Jakuje commented on tests/tests_set_common.yml
> +            - principal
please add asserts below to make sure the options are propagated to the configuration option and make sure the needed files are created.

2023-08-31 12:57 UTC, Jakuje commented on defaults/main.yml
> +sshd_trusted_user_ca_keys_list: []
comment does not math the default value here. Probably mention empty instead of null in the comment?

2023-09-01 09:19 UTC, EmyLIEUTAUD commented on tasks/certificates.yml
> +    mode: '0600'
I used the extension given as an example in the HashiCorp tutorial. In any case, the extension doesn't matter. Do you know a format that would be suitable without being confusing?

2023-09-01 17:52 UTC, Jakuje commented on tests/tests_set_common.yml
> +            - principal
Thanks. Given how simple the templates are, I do not think we need to check the content.

2023-09-01 17:53 UTC, Jakuje commented on tasks/certificates.yml
> +    mode: '0600'
Generally the SSH public keys have the `.pub` extension so I would probably go with that one.

2023-09-04 11:24 UTC, spetrosi commented on templates/auth_principals.j2
> +{% for principal in item.value %}
```suggestion
{{ ansible_managed | comment }}
{% for principal in item.value %}
```
It's a good practice to add `{{ ansible_managed | comment }}` for the config file templates to notify people looking into it that this file is managed by ansible and that manual edits would be overwritten.
Is it a good idea to add it here?

2023-09-04 11:24 UTC, spetrosi commented on templates/trusted-user-ca-keys.pub.j2
> +{% for key in sshd_trusted_user_ca_keys_list %}
```suggestion
{{ ansible_managed | comment }}
{% for key in sshd_trusted_user_ca_keys_list %}
```

2023-09-06 08:18 UTC, mattwillsher requested changes
One spelling correctiong but otherwise lgtm

2023-09-06 08:18 UTC, mattwillsher commented on tasks/certificates.yml
> +- name: Create Pincipals directory
```suggestion
- name: Create Principals directory
```

2023-09-06 08:33 UTC, Jakuje requested changes

2023-09-06 08:33 UTC, Jakuje commented on examples/example-use-certificates.yml
> +          - ssh-rsa AAAAB3Nzxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxd65YFPTgb6xxbaIB4z9Vw==
I would propose to put here some real key instead of the xxxs. It does not have to be your key, just generate random ssh key with ssh-keygen and put a public key here. I would suggest to use ecdsa or ed25519 as they are shorter.

2023-09-06 08:33 UTC, Jakuje commented on tasks/certificates.yml
> +    dest: "{{ sshd['TrustedUserCAKeys'] }}"
All of the configuration options we have in this role work in both writing as `sshd['TrustedUserCAKeys']` as well as `sshd_TrustedUserCAKeys` so I think this part of the role should reflect this too. I was solving similar thing with hostkeys here:

https://github.com/willshersystems/ansible-sshd/blob/d54f51f32a34cb0c08c722c944dc616a3b1c1bcd/tasks/install.yml#L37-L52

The same applies for `AuthorizedPrincipalsFile` below.

2023-09-06 09:44 UTC, EmyLIEUTAUD commented on tasks/certificates.yml
> +    dest: "{{ sshd['TrustedUserCAKeys'] }}"
Should I add the to_json filter to maintain Python 2 compatibility?

2023-09-06 10:50 UTC, Jakuje commented on tasks/certificates.yml
> +    dest: "{{ sshd['TrustedUserCAKeys'] }}"
Yes please. I hope we will not need it but better be safe than sorry.

2023-09-06 11:45 UTC, spetrosi commented on tasks/certificates.yml
> +  loop: "{{ q('dict', sshd_principals) }}"
```suggestion
  loop: "{{ ('dict', sshd_principals) }}"
```
Is it a typo?

2023-09-06 11:45 UTC, spetrosi commented on tests/tests_set_common.yml
> +            that:
```suggestion
            that: authorizedprincipalsfile_stat.stat.exists
```

2023-09-06 11:45 UTC, spetrosi commented on tests/tests_set_common.yml
> +              - authorizedprincipalsfile_stat.stat.exists
```suggestion
```

2023-09-06 11:45 UTC, spetrosi commented on tests/tests_set_common.yml
> +            that:
```suggestion
            that: trustedusercakeys_file_stat.stat.exists
```

2023-09-06 11:45 UTC, spetrosi commented on tests/tests_set_common.yml
> +              - trustedusercakeys_file_stat.stat.exists
```suggestion
```

2023-09-06 13:41 UTC, EmyLIEUTAUD commented on tasks/certificates.yml
> +    dest: "{{ sshd['TrustedUserCAKeys'] }}"
Changes added: [d301935](https://github.com/willshersystems/ansible-sshd/pull/252/commits/d3019356d3d703906dbad8700319580d7c3ebdf9)

2023-09-06 14:03 UTC, EmyLIEUTAUD commented on tasks/certificates.yml
> +  loop: "{{ q('dict', sshd_principals) }}"
This was an old syntax we used, but it's no longer documented. I've modified it to make the code easier to understand.

2023-09-06 14:18 UTC, richm commented on tasks/certificates.yml
> +        mode: '0755'
If the directory already exists and has a more secure mode e.g. `'0700'` do you want this to change it?

2023-09-06 14:30 UTC, Jakuje reviewed
hope last nits to the wording of README. Then I would love to have the fixup commits slightly squashed as the commit series is getting long ...

2023-09-06 14:30 UTC, Jakuje commented on README.md
> +  PasswordAuthentication: false
I would leave out this line as it is not required for the certificate authentication (even though it might be a common to disable the passwords when deploying certificates).

2023-09-06 15:32 UTC, richm commented on tasks/certificates.yml
> +        mode: '0755'
> Would you prefer to not specify the mode and use the existing mode if the file exists, and otherwise use the default mode? Or should I add a task to check if the directory already exists, and change mode only if it's less secure?

We typically do the latter in other system roles (do a `stat`, then use `stat.mode` if `stat.exists`, else `0755`), but if `0755` is the default for sshd, and recommended, then I guess it is ok

2023-09-06 15:58 UTC, mattwillsher commented on tasks/certificates.yml
> +        mode: '0755'
Fwiw I think the role should declare it in line with good practice. 

Using what exists in my view can lead to spaghetti dependencies and unexpected outcomes. Let this role own the directory or else let something else take responsibility.

If there is variation across releases a distribution specific variable can be used with an override, common to how this is handled for other variant cases. A variable seems sensible here as it could be considered security sensitive to some.

2023-09-07 07:54 UTC, EmyLIEUTAUD commented on README.md
> +To learn more about SSH Certificate, here is a [nice tutorial from Hashicorp](https://www.hashicorp.com/blog/managing-ssh-access-at-scale-with-hashicorp-vault)
I think the first tutorial is good because we can see how to set up SSH user certificates. 

What do you think about also leaving the HashiCorp tutorial to explain the principles part? I think it's useful for understanding what they're for and how they can be set up. They are available in the open-source version of Vault.

2023-09-07 07:57 UTC, EmyLIEUTAUD commented on tasks/certificates.yml
> +        mode: '0755'
If I've understood correctly, I'll need to create a dedicated role for certificates so that the directories in question are no longer owned by root:root?

2023-09-07 14:25 UTC, Jakuje commented on .pre-commit-config.yaml
> +    rev: v6.17.2
please, keep the dependencies changes in at least separate commit (ideally separate PR).

2023-09-07 14:25 UTC, Jakuje commented on README.md
> +To learn more about SSH Certificate, here is a [nice tutorial from Hashicorp](https://www.hashicorp.com/blog/managing-ssh-access-at-scale-with-hashicorp-vault)
I am ok with both of the links. Thanks for the patience!

2023-09-07 14:31 UTC, Jakuje commented on tests/tests_set_common.yml
> +            that: authorizedprincipalsfile_stat.stat.exists
Given that we have now option to set also the modes/owners of the files, I would check it also here in the test.

But given that this test is growing out of the scope a bit, I would probably propose to split out the certificate to separate test (and thoughtfully test also the new owner/group/mode options that were recently introduced  -- it should not be that much code given that you already do the stat here.

2023-09-08 09:21 UTC, EmyLIEUTAUD commented on .pre-commit-config.yaml
> +    rev: v6.17.2
Version restored here: [610a356](https://github.com/willshersystems/ansible-sshd/pull/252/commits/610a356d48ac8089ed374937350b414dbe68461c]).

2023-09-08 13:38 UTC, mattwillsher requested changes
Minor ordering in docs but looks good to be otherwise.

I don't understand why the checkout action is showing the version change - have you rebased from main recently? It might resolve that

2023-09-08 13:38 UTC, mattwillsher commented on README.md
> +Use these variables to set the ownership and permissions for the Trusted User CA Keys directory. Defaults are respectively *0750*, *root* and *root*.
Default example order should have mode last, as with the other 3 cases

2023-09-08 13:50 UTC, mattwillsher approved these changes

2023-09-08 14:03 UTC, richm approved these changes

2023-09-08 14:41 UTC, EmyLIEUTAUD commented on tasks/certificates.yml
> +        mode: '0755'
By default, I've set the trusted user ca keys directory to 0755, since in tutorials this is often the ssh directory and if it's set to 0750 we can't connect to the machine.

2023-09-08 20:53 UTC, Jakuje approved these changes
code wise it looks good. I would prefer the fixups commits squashed, but if others are ok with the commit series. I do not want to block the changes

2023-09-11 13:39 UTC, merged

2023-09-11 13:40 UTC, mattwillsher commented
Thanks for all the work on this @EmyLIEUTAUD 

I'll get a new release out that includes this code in the few days.