fix: Avoid creation of runtime directories in home
willshersystems/ansible-sshd pull request #265
Opened 2023-10-23 16:34 UTC by Jakuje

Enhancement: Avoid creation of runtime directory in home

Reason: The d6abe9c0325183180e6f83ba14c28781b9e6c6b9 changed the directories to be relative, but did not update tasks

Result: The playbook should create the runtime directory in the right place.

Issue Tracker Tickets (Jira or BZ if any): #264

2023-10-23 18:18 UTC, richm commented on tasks/install.yml
> +        path: "/run/{{ __sshd_runtime_directory }}"
Is it ok to do this for all platforms, not just Ubuntu/Debian?

2023-10-23 18:24 UTC, Jakuje commented on tasks/install.yml
> +        path: "/run/{{ __sshd_runtime_directory }}"
The Fedora/RHEL do not have RuntimeDirectory in the service file and therefore they have the `__sshd_runtime_directory` empty, which should skip this task.

2023-10-23 18:25 UTC, richm approved these changes

2023-10-27 19:13 UTC, mattwillsher commented on tasks/install.yml
> +        path: "/run/{{ __sshd_runtime_directory }}"
According to 'Table 2. Automatic directory creation and environment variables' at https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html the value is always relative. 
This value is set in the unit file. 
The template for this always set the value. The default for the runtime directory is ~, which YAML should interpret as null. I don't know what Ansible does with it.

I suggest the unit file makes the Runtime values conditional on the runtime directory being not null, so excluding the value entirely if not set. 

If ~ isn't being interpreted as null - the test added implies that it isn't - maybe it should be set to something that will be or just an empty string and the template set to add the RunTime... value iff the corresponding var is non-empty string.

2023-10-27 19:14 UTC, mattwillsher requested changes
The systemd unit file shouldn't include Runtime values at all if they are not set/not present in the default unit files

2023-10-30 09:18 UTC, Jakuje commented
> The systemd unit file shouldn't include Runtime values at all if they are not set/not present in the default unit files

Good point. I will update the template and test to verify this.

In separate PR I will probably do some more cleanup of the service/socket files as they are quite outdated anyway and they need some improvements to match differences between distributions.

2023-10-30 10:40 UTC, Jakuje commented on tasks/install.yml
> +        path: "/run/{{ __sshd_runtime_directory }}"
My understanding and observation from the test is that the `~` is interpreted as null/none. 
I updated the test and the templates not to print these empty options.

2023-10-30 10:44 UTC, mattwillsher approved these changes
See comments on tests but the code changes LGTM

2023-10-30 10:44 UTC, mattwillsher commented on tests/tests_runtime_directory.yml
> +            path: ~/sshd
This can't happen with the new code. Test is unnecessary

2023-10-30 10:44 UTC, mattwillsher commented on tests/tests_runtime_directory.yml
> +            path: /run/~
I don't understand the need for this - if ~ is really null in Ansible this shouldn't occur. If ~ is not null in Ansible the default value should be changed

2023-10-30 10:50 UTC, Jakuje commented on tests/tests_runtime_directory.yml
> +            path: /run/~
This is the test that I introduced to really verify that the `~` is being treated specially and not as a `~` string as I could not find this anywhere explicitly mentioned. I do not think the meaning would change in the future ansible versions, but I think this wont hurt sanity-checking that unexpected directories are not created.

One though is that I should probably make sure it does not exist before invoking the role to avoid false positives if something in the system would start creating these.

2023-10-30 10:53 UTC, Jakuje commented on tests/tests_runtime_directory.yml
> +            path: ~/sshd
Right. Unless somebody will change the code again and we won't notice as in the past. This is a point of regression testing, making sure we do not re-introduce the old bugs we had in the past. Indeed, new ones can always lurk into the code, but it give at least some sanity. As in the other comment, I should probably make sure the path does not exist before running the role though.

I still find them useful, but if you insist, I can remove these.

2023-10-30 13:27 UTC, mattwillsher commented
No need to change just wondering about their value. More checks is better :)

2023-10-30 13:27 UTC, merged